# Generated by Django 5.0.6 on 2026-05-16 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr_master', '0006_employee_pay_months_per_year_override_and_more'),
        ('reward_cycle', '0004_rewardcycle_discretionary_pct'),
    ]

    operations = [
        migrations.CreateModel(
            name='FxRateMonthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_currency', models.CharField(help_text='源币种 HKD/SGD/EUR/JPY/USD…', max_length=8)),
                ('target_currency', models.CharField(help_text='目标币种 CNY 或 USD', max_length=8)),
                ('month', models.CharField(help_text='2026-03', max_length=7)),
                ('rate', models.DecimalField(decimal_places=6, help_text='1 quote = N target', max_digits=14)),
                ('source', models.CharField(default='MANUAL', max_length=16)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('locked_by_id', models.BigIntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'analytics_fx_rate_monthly',
                'indexes': [models.Index(fields=['target_currency', 'month'], name='analytics_f_target__c9fac6_idx')],
                'unique_together': {('quote_currency', 'target_currency', 'month')},
            },
        ),
        migrations.CreateModel(
            name='MarketSalaryReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_level_code', models.CharField(max_length=32)),
                ('region', models.CharField(max_length=64)),
                ('year', models.IntegerField()),
                ('p50_cny', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('p75_cny', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('p90_cny', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('source_note', models.CharField(blank=True, max_length=200)),
                ('uploaded_by_id', models.BigIntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'analytics_market_salary_ref',
                'unique_together': {('job_level_code', 'region', 'year')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeCompensationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('snapshot_kind', models.CharField(choices=[('ACTUAL', '已实发'), ('PROJECTED', 'Y+1 预测')], max_length=16)),
                ('annual_fixed_cny', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('annual_bonus_cny', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('annual_cash_cny', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('annual_rsu_value_cny', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('annual_total_comp_cny', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('perf_grade_code', models.CharField(blank=True, max_length=32)),
                ('pay_band', models.CharField(blank=True, max_length=16)),
                ('employee_category_1_snapshot', models.CharField(blank=True, max_length=16)),
                ('org_unit_snapshot_id', models.BigIntegerField(null=True)),
                ('source', models.CharField(default='DERIVED', max_length=32)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('derived_from_cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reward_cycle.rewardcycle')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_snapshots', to='hr_master.employee')),
            ],
            options={
                'db_table': 'analytics_emp_comp_snapshot',
                'indexes': [models.Index(fields=['year', 'snapshot_kind'], name='analytics_e_year_a2db8b_idx'), models.Index(fields=['org_unit_snapshot_id', 'year'], name='analytics_e_org_uni_91ee2e_idx')],
                'unique_together': {('employee', 'year', 'snapshot_kind')},
            },
        ),
    ]
