# Generated by Django 5.0.6 on 2026-05-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdjustmentBudgetCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('ANNUAL', '年度调薪'), ('PROMOTION', '晋升调薪')], max_length=16)),
                ('employee_category_1', models.CharField(choices=[('MANAGEMENT', '管理干部'), ('STAFF', '员工')], max_length=16)),
                ('budget_amount_cny', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('allocated_amount_cny', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
            ],
            options={
                'db_table': 'comp_adjustment_budget_cell',
            },
        ),
        migrations.CreateModel(
            name='AdjustmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('period', models.CharField(max_length=16)),
                ('status', models.CharField(default='DRAFT', max_length=32)),
                ('budget_total_cny', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('scope', models.JSONField(default=dict)),
                ('formula', models.JSONField(default=dict)),
                ('rounding_rule', models.CharField(default='ROUND_HALF_UP', max_length=16)),
                ('created_by_id', models.BigIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'comp_adjustment_plan',
            },
        ),
        migrations.CreateModel(
            name='AdjustmentProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_currency', models.CharField(default='CNY', max_length=8)),
                ('status', models.CharField(default='DRAFT', max_length=32)),
                ('proposer_id', models.BigIntegerField(null=True)),
                ('effective_date', models.DateField(null=True)),
                ('calculation_basis_snapshot', models.JSONField(default=dict)),
                ('current_salary', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('current_job_level_snapshot', models.CharField(blank=True, max_length=32)),
                ('job_level_promoted_snapshot', models.CharField(blank=True, max_length=32)),
                ('employee_category_1_snapshot', models.CharField(default='STAFF', max_length=16)),
                ('participates_annual_snapshot', models.BooleanField(default=True)),
                ('promotion_adjustment_pct', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('annual_suggested_pct', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('annual_manager_delta_pct', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('promotion_adjustment_amount_cny', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('annual_adjustment_amount_cny', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_special_case', models.BooleanField(default=False)),
                ('market_benchmark_note', models.JSONField(blank=True, null=True)),
                ('retention_reason', models.TextField(blank=True)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'comp_adjustment_proposal',
            },
        ),
    ]
