# Generated by Django 5.0.6 on 2026-05-08 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compensation_plan', '0001_initial'),
        ('hr_master', '0001_initial'),
        ('reward_cycle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustmentbudgetcell',
            name='reward_cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustment_budget_cells', to='reward_cycle.rewardcycle'),
        ),
        migrations.AddField(
            model_name='adjustmentplan',
            name='reward_cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustment_plans', to='reward_cycle.rewardcycle'),
        ),
        migrations.AddField(
            model_name='adjustmentproposal',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_master.employee'),
        ),
        migrations.AddField(
            model_name='adjustmentproposal',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='compensation_plan.adjustmentplan'),
        ),
        migrations.AlterUniqueTogether(
            name='adjustmentbudgetcell',
            unique_together={('reward_cycle', 'adjustment_type', 'employee_category_1')},
        ),
        migrations.AlterUniqueTogether(
            name='adjustmentproposal',
            unique_together={('plan', 'employee')},
        ),
    ]
