# Generated by Django 5.0.6 on 2026-05-09 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensation_plan', '0002_initial'),
        ('iam', '0001_initial'),
        ('reward_cycle', '0002_rewardcycle_executed_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='adjustmentbudgetcell',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='adjustmentbudgetcell',
            name='department',
            field=models.ForeignKey(blank=True, help_text='NULL = 公司总预算层；非 NULL = 该部门分配额', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustment_budget_cells', to='iam.orgunit'),
        ),
        migrations.AlterUniqueTogether(
            name='adjustmentbudgetcell',
            unique_together={('reward_cycle', 'adjustment_type', 'employee_category_1', 'department')},
        ),
    ]
