# Generated by Django 5.0.6 on 2026-05-13 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensation_plan', '0003_add_department_dimension'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustmentbudgetcell',
            name='distribution_rule',
            field=models.CharField(blank=True, choices=[('MANUAL', '手动'), ('HEADCOUNT', '按人头'), ('SALARY_TOTAL', '按薪资基数')], default='MANUAL', help_text='仅公司层 cell（department=NULL）使用，记录最近一次下发规则', max_length=16),
        ),
        migrations.AddField(
            model_name='adjustmentbudgetcell',
            name='reclaimed_amount_cny',
            field=models.DecimalField(decimal_places=2, default=0, help_text='EXECUTE 后回收的未用预算（仅目标层 cell）', max_digits=16),
        ),
    ]
