# Generated by Django 5.0.6 on 2026-05-15 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensation_plan', '0004_distribution_rule_and_reclaim'),
        ('hr_master', '0004_categoryscheme_employeecategory_and_more'),
        ('reward_cycle', '0003_rewardcycle_category_scheme'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCategoryFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('ANNUAL', '年度调薪'), ('PROMOTION', '晋升调薪')], max_length=16)),
                ('factor', models.DecimalField(decimal_places=4, default=1, help_text='乘在基准比例之上, 1.0000 = 不调整', max_digits=6)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustment_factors', to='hr_master.employeecategory')),
                ('reward_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_factors', to='reward_cycle.rewardcycle')),
            ],
            options={
                'db_table': 'comp_employee_category_factor',
                'indexes': [models.Index(fields=['reward_cycle', 'adjustment_type'], name='comp_employ_reward__40fe73_idx')],
                'unique_together': {('reward_cycle', 'category', 'adjustment_type')},
            },
        ),
        migrations.CreateModel(
            name='RegionalAdjustmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(help_text='LegalEntity.country, 如 CN / US / SG', max_length=8)),
                ('adjustment_type', models.CharField(choices=[('ANNUAL', '年度调薪'), ('PROMOTION', '晋升调薪')], max_length=16)),
                ('base_pct', models.DecimalField(decimal_places=4, help_text='例如 0.0500 表示 5%', max_digits=6)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reward_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regional_adjustment_rules', to='reward_cycle.rewardcycle')),
            ],
            options={
                'db_table': 'comp_regional_adjustment_rule',
                'indexes': [models.Index(fields=['reward_cycle', 'adjustment_type'], name='comp_region_reward__209af8_idx')],
                'unique_together': {('reward_cycle', 'country', 'adjustment_type')},
            },
        ),
    ]
