# Generated by Django 5.0.6 on 2026-05-15 11:20

import apps.compensation_plan.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensation_plan', '0005_employeecategoryfactor_regionaladjustmentrule'),
        ('hr_master', '0005_seed_default_category_scheme'),
        ('reward_cycle', '0003_rewardcycle_category_scheme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adjustmentplan',
            name='budget_total_cny',
        ),
        migrations.RemoveField(
            model_name='adjustmentplan',
            name='scope',
        ),
        migrations.AddField(
            model_name='adjustmentplan',
            name='perf_grades',
            field=models.JSONField(default=apps.compensation_plan.models.default_perf_grades, help_text='绩效档位列表 [{code, label, sort_order}], 默认 5 档 (5 星 -> 1 星)'),
        ),
        migrations.CreateModel(
            name='AdjustmentMatrixCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perf_grade_code', models.CharField(max_length=32)),
                ('pay_band', models.CharField(choices=[('BELOW_P50', 'P50 以下'), ('P50_P75', 'P50 - P75'), ('ABOVE_P75', 'P75 以上')], max_length=16)),
                ('coef_low', models.DecimalField(decimal_places=4, max_digits=5)),
                ('coef_high', models.DecimalField(decimal_places=4, max_digits=5)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustment_matrix_cells', to='hr_master.employeecategory')),
                ('reward_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustment_matrix_cells', to='reward_cycle.rewardcycle')),
            ],
            options={
                'db_table': 'comp_adjustment_matrix_cell',
                'indexes': [models.Index(fields=['reward_cycle', 'category'], name='comp_adjust_reward__cecb4a_idx')],
                'unique_together': {('reward_cycle', 'category', 'perf_grade_code', 'pay_band')},
            },
        ),
    ]
