# Generated by Django 5.0.6 on 2026-05-15 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensation_plan', '0006_reorganize_plan_with_matrix'),
        ('iam', '0007_session_revocation'),
        ('reward_cycle', '0003_rewardcycle_category_scheme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('ANNUAL', '年度调薪'), ('PROMOTION', '晋升调薪')], max_length=16)),
                ('override_amount_cny', models.DecimalField(decimal_places=2, max_digits=16)),
                ('source', models.CharField(choices=[('IMPORTED', '已导入'), ('DERIVED', '派生')], default='IMPORTED', max_length=16)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('department', models.ForeignKey(help_text='必须 type=DEPT；不允许 NULL (未分配部门不可覆盖)', on_delete=django.db.models.deletion.CASCADE, related_name='budget_overrides', to='iam.orgunit')),
                ('reward_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_overrides', to='reward_cycle.rewardcycle')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_overrides_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comp_budget_override',
                'indexes': [models.Index(fields=['reward_cycle', 'adjustment_type'], name='comp_budget_reward__c7e3ed_idx')],
                'unique_together': {('reward_cycle', 'department', 'adjustment_type')},
            },
        ),
    ]
