# Generated by Django 5.0.6 on 2026-05-08 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iam', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=32, unique=True)),
                ('band', models.CharField(blank=True, max_length=32)),
                ('p50', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('p75', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('p90', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('min_salary', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('mid_salary', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('max_salary', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'hr_job_grade',
            },
        ),
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=8)),
                ('jurisdiction', models.CharField(blank=True, max_length=64)),
                ('default_currency', models.CharField(default='CNY', max_length=8)),
                ('tax_id', models.CharField(blank=True, max_length=64)),
                ('address', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'hr_legal_entity',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_no', models.CharField(max_length=32, unique=True)),
                ('name_cn', models.CharField(max_length=64)),
                ('name_en', models.CharField(blank=True, max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('dept_name', models.CharField(blank=True, max_length=128)),
                ('center_name', models.CharField(blank=True, max_length=128)),
                ('team_name', models.CharField(blank=True, max_length=128)),
                ('work_location', models.CharField(blank=True, max_length=128)),
                ('pay_country_region', models.CharField(blank=True, max_length=64)),
                ('pay_currency', models.CharField(default='CNY', max_length=8)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='ACTIVE', max_length=16)),
                ('job_family', models.CharField(blank=True, max_length=64)),
                ('job_level_current', models.CharField(blank=True, max_length=32)),
                ('job_level_promoted', models.CharField(blank=True, max_length=32)),
                ('position_current', models.CharField(blank=True, max_length=64)),
                ('position_promoted', models.CharField(blank=True, max_length=64)),
                ('is_promoted', models.BooleanField(default=False)),
                ('promotion_category', models.CharField(choices=[('VERTICAL', '纵向晋升'), ('LATERAL', '横向调动'), ('NONE', '未晋升')], default='NONE', max_length=16)),
                ('participates_annual_adjustment', models.BooleanField(default=True)),
                ('employee_category_1', models.CharField(choices=[('MANAGEMENT', '管理干部'), ('STAFF', '员工')], default='STAFF', max_length=16)),
                ('employee_category_2', models.CharField(blank=True, max_length=32)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='hr_master.employee')),
                ('org_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iam.orgunit')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('legal_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_master.legalentity')),
            ],
            options={
                'db_table': 'hr_employee',
            },
        ),
        migrations.CreateModel(
            name='CompensationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField()),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=14)),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=14)),
                ('allowance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='CNY', max_length=8)),
                ('source', models.CharField(default='MANUAL', max_length=16)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_master.compensationrecord')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensation_records', to='hr_master.employee')),
            ],
            options={
                'db_table': 'hr_compensation_record',
            },
        ),
        migrations.CreateModel(
            name='PerformanceRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.IntegerField()),
                ('period_half', models.CharField(choices=[('H1', '上半年'), ('H2', '下半年')], max_length=4)),
                ('rating', models.CharField(blank=True, max_length=8)),
                ('final_score', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('source', models.CharField(default='IMPORT', max_length=16)),
                ('locked_at', models.DateTimeField(null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perf_ratings', to='hr_master.employee')),
            ],
            options={
                'db_table': 'hr_performance_rating',
                'unique_together': {('employee', 'period_year', 'period_half')},
            },
        ),
    ]
