# Generated by Django 5.0.6 on 2026-05-12 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('order', models.IntegerField(help_text='排序权重，小的在前')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'hr_level_band',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PositionGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('order', models.IntegerField(default=0)),
                ('suggested_min_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('suggested_max_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('level_band', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='position_grades', to='hr_master.levelband')),
            ],
            options={
                'db_table': 'hr_position_grade',
                'ordering': ['level_band__order', 'order'],
            },
        ),
    ]
