# Generated by Django 5.0.6 on 2026-05-12 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_master', '0002_dictionaries_and_freeze'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeFreeze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('PROBATION', '试用期'), ('LEAVING', '离职流转'), ('LEGAL_HOLD', '法务调查'), ('LONG_LEAVE', '长期休假'), ('OTHER', '其他')], max_length=16)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='null 表示开口冻结', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freezes', to='hr_master.employee')),
            ],
            options={
                'db_table': 'hr_employee_freeze',
                'indexes': [models.Index(fields=['employee', 'start_date'], name='hr_employee_employe_0c1a0b_idx')],
            },
        ),
    ]
