# Generated by Django 5.0.6 on 2026-05-15 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_master', '0003_employee_freeze'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('ACTIVE', '启用'), ('ARCHIVED', '归档')], default='ACTIVE', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hr_category_scheme',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='方案内唯一, 如 MGMT/STAFF/SENIOR/JUNIOR', max_length=32)),
                ('name', models.CharField(help_text='如 干部/员工/高级员工', max_length=64)),
                ('sort_order', models.IntegerField(default=0)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='hr_master.categoryscheme')),
            ],
            options={
                'db_table': 'hr_employee_category',
                'ordering': ['scheme_id', 'sort_order'],
                'unique_together': {('scheme', 'code')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeCategoryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='hr_master.employeecategory')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_assignments', to='hr_master.employee')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='hr_master.categoryscheme')),
            ],
            options={
                'db_table': 'hr_employee_category_assignment',
                'indexes': [models.Index(fields=['scheme', 'category'], name='hr_employee_scheme__46816d_idx')],
                'unique_together': {('employee', 'scheme')},
            },
        ),
    ]
