# Generated by Django 5.0.6 on 2026-05-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_master', '0005_seed_default_category_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pay_months_per_year_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='个别合同覆盖法人主体默认值；NULL 表示走 legal_entity.fixed_pay_months_per_year', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='fixed_pay_months_per_year',
            field=models.DecimalField(decimal_places=2, default=12, help_text='法定固薪月数：中国大陆 12，香港 13，西班牙/希腊 14', max_digits=4),
        ),
    ]
