# Generated by Django 5.0.6 on 2026-05-08 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalChainTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario', models.CharField(choices=[('ADJUSTMENT', 'Adjustment'), ('BONUS', 'Bonus'), ('LTI', 'LTI'), ('REWARD_CYCLE', 'Reward Cycle'), ('DELEGATION', 'Delegation')], max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('status', models.CharField(default='ACTIVE', max_length=16)),
                ('version', models.IntegerField(default=1)),
                ('is_default', models.BooleanField(default=False)),
                ('nodes', models.JSONField(default=list)),
                ('effective_from', models.DateField(null=True)),
                ('effective_to', models.DateField(null=True)),
            ],
            options={
                'db_table': 'approval_chain_template',
            },
        ),
        migrations.CreateModel(
            name='ApprovalInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type', models.CharField(max_length=32)),
                ('subject_id', models.BigIntegerField()),
                ('current_node', models.IntegerField(default=0)),
                ('status', models.CharField(default='RUNNING', max_length=32)),
                ('over_budget_flag', models.BooleanField(default=False)),
                ('over_budget_details', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='approval.approvalchaintemplate')),
            ],
            options={
                'db_table': 'approval_instance',
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_index', models.IntegerField()),
                ('approver_user_id', models.BigIntegerField()),
                ('action', models.CharField(choices=[('APPROVE', 'Approve'), ('REJECT_BATCH', 'Reject Batch'), ('REJECT_INDIVIDUAL', 'Reject Individual'), ('REJECT_WITH_COMMENT', 'Reject With Comment')], max_length=32)),
                ('comment', models.TextField(blank=True)),
                ('acted_at', models.DateTimeField(auto_now_add=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='approval.approvalinstance')),
            ],
            options={
                'db_table': 'approval_step',
            },
        ),
    ]
