# Generated by Django 5.0.6 on 2026-05-08 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compensation_plan', '0001_initial'),
        ('lti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('period', models.CharField(max_length=16)),
                ('status', models.CharField(default='DRAFT', max_length=32)),
                ('scope', models.JSONField(default=dict)),
                ('total_comp_config', models.JSONField(default=dict)),
                ('created_by_id', models.BigIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linked_adjustment_plan', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_cycle_link', to='compensation_plan.adjustmentplan')),
                ('linked_lti_plan', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_cycle_link', to='lti.ltiplan')),
            ],
            options={
                'db_table': 'reward_cycle',
            },
        ),
    ]
