# Generated by Django 5.0.6 on 2026-05-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward_cycle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardcycle',
            name='executed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
