# Generated by Django 5.0.6 on 2026-05-15 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_master', '0004_categoryscheme_employeecategory_and_more'),
        ('reward_cycle', '0002_rewardcycle_executed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardcycle',
            name='category_scheme',
            field=models.ForeignKey(blank=True, help_text='该周期使用的员工类别方案；规则、预算单元的 category_id 都必须落在此方案下', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reward_cycles', to='hr_master.categoryscheme'),
        ),
    ]
