# Generated by Django 5.0.6 on 2026-05-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward_cycle', '0003_rewardcycle_category_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardcycle',
            name='discretionary_pct',
            field=models.DecimalField(decimal_places=4, default=0.1, help_text='部门 head 机动盘占预算池比例 (默认 10%); 矩阵建议占 1-discretionary_pct', max_digits=5),
        ),
    ]
