# Generated by Django 5.0.6 on 2026-05-18 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus_pool', '0002_bonusplan_created_by_id_bonusplan_reward_cycle_and_more'),
        ('reward_cycle', '0004_rewardcycle_discretionary_pct'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardcycle',
            name='linked_bonus_plan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_cycle_link', to='bonus_pool.bonusplan'),
        ),
    ]
