# Generated by Django 5.0.6 on 2026-05-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BonusPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('period', models.CharField(max_length=16)),
                ('status', models.CharField(default='DRAFT', max_length=32)),
                ('budget_total_cny', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('scope', models.JSONField(blank=True, default=dict)),
                ('formula', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bonus_plan',
            },
        ),
    ]
