# Generated by Django 5.0.6 on 2026-05-18 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus_pool', '0001_initial'),
        ('hr_master', '0006_employee_pay_months_per_year_override_and_more'),
        ('iam', '0008_user_preferred_language'),
        ('reward_cycle', '0004_rewardcycle_discretionary_pct'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bonusplan',
            name='created_by_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bonusplan',
            name='reward_cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonus_plans', to='reward_cycle.rewardcycle'),
        ),
        migrations.CreateModel(
            name='BonusBudgetCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_category_1', models.CharField(choices=[('MANAGEMENT', '管理干部'), ('STAFF', '员工')], max_length=16)),
                ('budget_amount_cny', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('allocated_amount_cny', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('distribution_rule', models.CharField(blank=True, choices=[('MANUAL', '手动'), ('HEADCOUNT', '按人头'), ('SALARY_TOTAL', '按薪资基数')], default='MANUAL', help_text='仅公司层 cell 使用，记录最近一次下发规则', max_length=16)),
                ('reclaimed_amount_cny', models.DecimalField(decimal_places=2, default=0, help_text='EXECUTE 后回收的未用预算（仅目标层 cell）', max_digits=16)),
                ('reward_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_budget_cells', to='reward_cycle.rewardcycle')),
                ('target_org_unit', models.ForeignKey(blank=True, help_text='NULL = 公司层；非 NULL = 该 DEPT/CENTER 单元的下发额度', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bonus_budget_cells', to='iam.orgunit')),
            ],
            options={
                'db_table': 'bonus_budget_cell',
                'unique_together': {('reward_cycle', 'employee_category_1', 'target_org_unit')},
            },
        ),
        migrations.CreateModel(
            name='BonusBudgetOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('override_amount_cny', models.DecimalField(decimal_places=2, max_digits=16)),
                ('source', models.CharField(choices=[('IMPORTED', '已导入'), ('DERIVED', '派生')], default='IMPORTED', max_length=16)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('department', models.ForeignKey(help_text='必须 type=DEPT；不允许 NULL (未分配部门不可覆盖)', on_delete=django.db.models.deletion.CASCADE, related_name='bonus_budget_overrides', to='iam.orgunit')),
                ('reward_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_budget_overrides', to='reward_cycle.rewardcycle')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonus_budget_overrides_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bonus_budget_override',
                'indexes': [models.Index(fields=['reward_cycle'], name='bonus_budge_reward__a648a6_idx')],
                'unique_together': {('reward_cycle', 'department')},
            },
        ),
        migrations.CreateModel(
            name='BonusCategoryFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_category_1', models.CharField(choices=[('MANAGEMENT', '管理干部'), ('STAFF', '员工')], max_length=16)),
                ('factor', models.DecimalField(decimal_places=4, default=1, help_text='乘在基准月数之上, 1.0000 = 不调整', max_digits=6)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reward_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_category_factors', to='reward_cycle.rewardcycle')),
            ],
            options={
                'db_table': 'bonus_category_factor',
                'indexes': [models.Index(fields=['reward_cycle'], name='bonus_categ_reward__11f29f_idx')],
                'unique_together': {('reward_cycle', 'employee_category_1')},
            },
        ),
        migrations.CreateModel(
            name='BonusProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='DRAFT', max_length=32)),
                ('proposer_id', models.BigIntegerField(null=True)),
                ('suggested_amount_cny', models.DecimalField(decimal_places=2, default=0, help_text='规则派生的建议金额 = monthly_salary × base_months × factor', max_digits=14)),
                ('manager_delta_amount_cny', models.DecimalField(decimal_places=2, default=0, help_text='经理可调增减额（正负）', max_digits=14)),
                ('final_amount_cny', models.DecimalField(decimal_places=2, default=0, help_text='EXECUTE 时锁定 = suggested + manager_delta', max_digits=14)),
                ('employee_category_1_snapshot', models.CharField(default='STAFF', max_length=16)),
                ('country_snapshot', models.CharField(blank=True, max_length=8)),
                ('monthly_salary_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_master.employee')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='bonus_pool.bonusplan')),
            ],
            options={
                'db_table': 'bonus_proposal',
                'unique_together': {('plan', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='RegionalBonusRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(help_text='LegalEntity.country, 如 CN / US / SG', max_length=8)),
                ('base_months', models.DecimalField(decimal_places=4, help_text='例如 1.5000 表示 1.5 个月薪', max_digits=6)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reward_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regional_bonus_rules', to='reward_cycle.rewardcycle')),
            ],
            options={
                'db_table': 'bonus_regional_rule',
                'indexes': [models.Index(fields=['reward_cycle'], name='bonus_regio_reward__60081e_idx')],
                'unique_together': {('reward_cycle', 'country')},
            },
        ),
    ]
