# Generated by Django 5.0.6 on 2026-05-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='base_field_set',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(choices=[('HR_ADMIN', '薪酬 HR'), ('DEPT_HEAD', '部门负责人'), ('CENTER_HEAD', '中心负责人'), ('GROUP_LEAD', '组长'), ('EMPLOYEE', '员工'), ('FINANCE', '财务'), ('AUDITOR', '审计员'), ('HRBP', 'HRBP'), ('EXEC', '高管'), ('SYS_ADMIN', '系统管理员')], max_length=32, unique=True),
        ),
    ]
