# Generated by Django 5.0.6 on 2026-05-11 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0003_seed_system_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldPermissionGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_fields', models.JSONField(default=list, help_text='必须是 RSU_FIELD_GROUP 子集')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('center', models.ForeignKey(help_text='被授权范围限定为此中心', on_delete=django.db.models.deletion.PROTECT, related_name='field_grants', to='iam.orgunit')),
                ('grantee', models.ForeignKey(help_text='中心负责人 user_id', on_delete=django.db.models.deletion.PROTECT, related_name='grants_received', to=settings.AUTH_USER_MODEL)),
                ('granter', models.ForeignKey(help_text='部门负责人 user_id', on_delete=django.db.models.deletion.PROTECT, related_name='grants_issued', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'iam_field_permission_grant',
            },
        ),
        migrations.AddConstraint(
            model_name='fieldpermissiongrant',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('grantee', 'center'), name='uniq_active_grant_per_grantee_center'),
        ),
    ]
