# Generated by Django 5.0.6 on 2026-05-12 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0004_field_permission_grant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgunit',
            name='leader_user',
            field=models.ForeignKey(blank=True, help_text='主负责人冗余字段；兼任与多负责人通过 OrgUnitManager 表达', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orgunit',
            name='type',
            field=models.CharField(choices=[('COMPANY', '公司'), ('SUBSIDIARY', '分公司'), ('DEPT', '部门'), ('CENTER', '中心'), ('TEAM', '组'), ('EMPLOYEE_LEAF', '员工节点')], max_length=16),
        ),
        migrations.CreateModel(
            name='OrgUnitManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_in_unit', models.CharField(choices=[('DEPT_HEAD', '部门负责人'), ('CENTER_HEAD', '中心负责人'), ('GROUP_LEAD', '组长')], max_length=16)),
                ('is_primary', models.BooleanField(default=False)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_units', to=settings.AUTH_USER_MODEL)),
                ('org_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='iam.orgunit')),
            ],
            options={
                'db_table': 'iam_org_unit_manager',
            },
        ),
        migrations.AddConstraint(
            model_name='orgunitmanager',
            constraint=models.UniqueConstraint(condition=models.Q(('effective_to__isnull', True), ('is_primary', True)), fields=('org_unit',), name='uniq_active_primary_per_unit'),
        ),
    ]
