# Generated by Django 5.0.6 on 2026-05-12 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0005_org_unit_manager_and_leaf'),
    ]

    operations = [
        migrations.CreateModel(
            name='MfaChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('LOGIN', '登录'), ('EXPORT', '导出敏感数据'), ('FINAL_APPROVE', '终审审批'), ('ROLE_ASSIGN', '角色变更')], max_length=16)),
                ('code_hash', models.CharField(blank=True, help_text='TOTP 不存明文', max_length=128)),
                ('status', models.CharField(choices=[('PENDING', '待验证'), ('VERIFIED', '已通过'), ('FAILED', '失败'), ('EXPIRED', '已过期')], default='PENDING', max_length=16)),
                ('attempts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'iam_mfa_challenge',
                'indexes': [models.Index(fields=['user', 'status'], name='iam_mfa_cha_user_id_8e20da_idx')],
            },
        ),
    ]
