# Generated by Django 5.0.6 on 2026-05-12 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0006_mfa_challenge'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionRevocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('reason', models.CharField(choices=[('LOGOUT', '用户登出'), ('ADMIN_KICK', '管理员强制下线'), ('MFA_FAIL', 'MFA 连续失败'), ('ROLE_CHANGE', '角色变更')], max_length=16)),
                ('revoked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revocations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'iam_session_revocation',
            },
        ),
    ]
