# Generated by Django 5.0.6 on 2026-05-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0007_session_revocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('zh', '中文'), ('en', 'English')], default='zh', max_length=5),
        ),
    ]
