# Generated by Django 5.0.6 on 2026-05-08 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr_master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LTIBudgetCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_category_1', models.CharField(choices=[('MANAGEMENT', '管理干部'), ('STAFF', '员工')], max_length=16)),
                ('headcount_quota', models.IntegerField(default=0)),
                ('shares_quota_ads', models.BigIntegerField(default=0)),
                ('headcount_used', models.IntegerField(default=0)),
                ('shares_used_ads', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'lti_budget_cell',
            },
        ),
        migrations.CreateModel(
            name='LTIPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('grant_date', models.DateField()),
                ('total_shares', models.BigIntegerField(default=0)),
                ('share_unit', models.CharField(default='ADS', max_length=8)),
                ('unit_price_at_grant', models.DecimalField(decimal_places=4, max_digits=10)),
                ('vesting_schedule', models.JSONField(default=dict)),
                ('cliff_months', models.IntegerField(default=12)),
                ('plan_doc_url', models.TextField(blank=True)),
                ('stock_code', models.CharField(blank=True, max_length=16)),
            ],
            options={
                'db_table': 'lti_plan',
            },
        ),
        migrations.CreateModel(
            name='StockPriceMonthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=16)),
                ('month', models.CharField(max_length=7)),
                ('closing_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('source', models.CharField(default='MARKET', max_length=16)),
                ('locked_by_id', models.BigIntegerField(null=True)),
                ('locked_at', models.DateTimeField(null=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'lti_stock_price_monthly',
            },
        ),
        migrations.CreateModel(
            name='VestingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('scheduled_shares', models.IntegerField()),
                ('actual_date', models.DateField(null=True)),
                ('actual_shares', models.IntegerField(null=True)),
                ('status', models.CharField(default='PENDING', max_length=16)),
            ],
            options={
                'db_table': 'lti_vesting_event',
            },
        ),
        migrations.CreateModel(
            name='EmployeeAck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type', models.CharField(max_length=16)),
                ('subject_id', models.BigIntegerField()),
                ('acked_at', models.DateTimeField(auto_now_add=True)),
                ('signature_hash', models.CharField(blank=True, max_length=64)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_master.employee')),
            ],
            options={
                'db_table': 'lti_employee_ack',
            },
        ),
        migrations.CreateModel(
            name='LTIGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='PROPOSED', max_length=16)),
                ('is_eligible', models.BooleanField(default=True)),
                ('grant_tier', models.CharField(blank=True, max_length=8)),
                ('suggested_range_min_ads', models.IntegerField(default=0)),
                ('suggested_range_max_ads', models.IntegerField(default=0)),
                ('granted_ads', models.IntegerField(default=0)),
                ('employee_category_1_snapshot', models.CharField(default='STAFF', max_length=16)),
                ('stock_code', models.CharField(blank=True, max_length=16)),
                ('unit_price_at_grant', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('pending_shares_by_year', models.JSONField(default=dict)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_master.employee')),
            ],
            options={
                'db_table': 'lti_grant',
            },
        ),
    ]
