# Generated by Django 5.0.6 on 2026-05-08 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lti', '0001_initial'),
        ('reward_cycle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ltiplan',
            name='reward_cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lti_plans', to='reward_cycle.rewardcycle'),
        ),
        migrations.AddField(
            model_name='ltigrant',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='lti.ltiplan'),
        ),
        migrations.AddField(
            model_name='ltibudgetcell',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_cells', to='lti.ltiplan'),
        ),
        migrations.AlterUniqueTogether(
            name='stockpricemonthly',
            unique_together={('stock_code', 'month')},
        ),
        migrations.AddField(
            model_name='vestingevent',
            name='grant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vesting_events', to='lti.ltigrant'),
        ),
        migrations.AlterUniqueTogether(
            name='employeeack',
            unique_together={('subject_type', 'subject_id', 'employee')},
        ),
        migrations.AlterUniqueTogether(
            name='ltigrant',
            unique_together={('plan', 'employee')},
        ),
        migrations.AlterUniqueTogether(
            name='ltibudgetcell',
            unique_together={('plan', 'employee_category_1')},
        ),
    ]
