# Generated by Django 5.0.6 on 2026-05-13 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0007_session_revocation'),
        ('lti', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ltibudgetcell',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ltibudgetcell',
            name='distribution_rule',
            field=models.CharField(blank=True, choices=[('MANUAL', '手动'), ('HEADCOUNT', '按人头'), ('SALARY_TOTAL', '按薪资基数')], default='MANUAL', help_text='仅公司层 cell 使用，记录最近一次下发规则', max_length=16),
        ),
        migrations.AddField(
            model_name='ltibudgetcell',
            name='reclaimed_shares_ads',
            field=models.BigIntegerField(default=0, help_text='EXECUTE 后回收的未授予股数（仅目标层）'),
        ),
        migrations.AddField(
            model_name='ltibudgetcell',
            name='target_org_unit',
            field=models.ForeignKey(blank=True, help_text='NULL = 公司层；非 NULL = 该 DEPT/CENTER 单元的下发额度', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lti_budget_cells', to='iam.orgunit'),
        ),
        migrations.AlterUniqueTogether(
            name='ltibudgetcell',
            unique_together={('plan', 'employee_category_1', 'target_org_unit')},
        ),
    ]
